FROM resin/%%RESIN_MACHINE_NAME%%-node:6-slim

RUN apt-get update && apt-get install -yq \
    python make g++ && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache clean && rm -rf /tmp/*

COPY lib lib
COPY index.js index.js

ENV INITSYSTEM on

CMD ["npm", "start"]
